# 继承的配置文件。本配置文件中未定义的配置项将从继承的配置文件中继承。
extends = []
# 混入的配置文件。覆盖本配置文件中的同名配置项。
mixin = []

["Config/CcxcConfig"]
# HTTP服务端口
HttpPort = ""
# Redis服务器连接字符串
RedisConnStr = ""
# 数据库连接字符串，默认：Server=localhost;User=root;Database=ccxc_db;Port=3306;Password=lp1234xy;Charset=utf8mb4;ConvertZeroDateTime=True
DbConnStr = ""
# 调试模式：调试模式打开时，捕获的异常详情将通过HTTP直接返回给客户端，关闭时只返回简单错误消息和500提示码。True-打开 False-关闭，默认为False
DebugMode = ""
# 图片存储目录，上传的图片将会存放在这里。默认：D:/MyWorks/ccxc/static.ccxc.online/static/images
ImageStorage = ""
# 图片访问前缀。默认：https://static.ccbc11.test/static/images/
ImagePrefix = ""
# 密码Hash种子1，请自由设置，设置后不要修改
PassHashKey1 = ""
# 密码Hash种子2，请自由设置，设置后不要修改
PassHashKey2 = ""
# 用户Session有效期，单位秒，默认7200。
UserSessionTimeout = ""
# 默认罚时时间，单位小时，默认12.0
PenaltyDefault = ""
# 开赛时间，Unix时间戳（毫秒）
StartTime = ""
# 完赛时间，Unix时间戳（毫秒）
EndTime = ""
# 阿里云邮件推送服务Access Key
AliyunDmAccessKey = ""
# 阿里云邮件推送服务Access Secret
AliyunDmAccessSecret = ""
# 题目部分独立前端地址前缀（仅域名，不要以/结尾），默认：https://puzzle.ccbc11.test
GamePrefix = ""
